table Clientes
	lineageTag: b1506d63-1965-41e5-b111-cd11193d0f1c

	column IDCliente
		isHidden
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: IDCliente

	column Cliente
		dataType: string
		summarizeBy: none
		sourceColumn: Cliente

	column Segmento
		dataType: string
		summarizeBy: none
		sourceColumn: Segmento

	column País
		dataType: string
		summarizeBy: none
		sourceColumn: País

	column Ciudad
		dataType: string
		summarizeBy: none
		sourceColumn: Ciudad

	column Ciudad/País = Clientes[Ciudad]&","&Clientes[País]
		summarizeBy: none

	partition Clientes-1fd0fb07-b0c3-4281-a89a-6c4d4c7f087b = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Data\AnalisisVentas\Clientes.csv"),[Delimiter=";", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}}),
				    #"Filas superiores quitadas" = Table.Skip(#"Tipo cambiado",1),
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Filas superiores quitadas", [PromoteAllScalars=true]),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"IDCliente", Int64.Type}, {"Cliente", type text}, {"Segmento", type text}, {"Teléfono", Int64.Type}, {"Ubicación", type text}}),
				    #"Dividir columna por delimitador" = Table.SplitColumn(#"Tipo cambiado1", "Ubicación", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), {"Ubicación.1", "Ubicación.2"}),
				    #"Separa Ubicación" = Table.TransformColumnTypes(#"Dividir columna por delimitador",{{"Ubicación.1", type text}, {"Ubicación.2", type text}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Separa Ubicación",{{"Ubicación.1", "Ciudad"}, {"Ubicación.2", "País"}}),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Columnas con nombre cambiado",{"IDCliente", "Cliente", "Segmento", "Teléfono", "País", "Ciudad"})
				in
				    #"Columnas reordenadas"
