table Vendedores
	column IDVendedor
		isHidden
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: IDVendedor

	column Vendedor
		dataType: string
		summarizeBy: none
		sourceColumn: Vendedor

	partition Vendedores-6998fefe-020c-4c6c-b754-2c44053ca66a = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Data\AnalisisVentas\Ejer PBI.xlsx"), null, true),
				    Vendedores_Sheet = Origen{[Item="Vendedores",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Vendedores_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"IDVendedor", Int64.Type}, {"Vendedor", type text}})
				in
				    #"Tipo cambiado"
