table Canales
	lineageTag: 4972d943-4050-4687-92c5-cc6b3bf8a131

	column IDCanal
		isHidden
		dataType: int64
		formatString: 0
		lineageTag: 3fa03735-10b4-4fea-a083-36b9b96c9835
		summarizeBy: none
		sourceColumn: IDCanal

		annotation SummarizationSetBy = Automatic

	column Canal
		dataType: string
		lineageTag: 73f5f2fc-282c-47eb-8f09-bfbe1b8886f2
		summarizeBy: none
		sourceColumn: Canal

		annotation SummarizationSetBy = Automatic

	partition Canales-69fddee5-6810-4b76-89b8-98ed683eae6b = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Data\AnalisisVentas\Ejer PBI.xlsx"), null, true),
				    Canales_Sheet = Origen{[Item="Canales",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Canales_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"IDCanal", Int64.Type}, {"Canal", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

