table Cobranzas
	lineageTag: 44f2143a-729b-454d-9ebd-fc145cbfcff0

	column IDCobranza
		isHidden
		dataType: int64
		formatString: 0
		lineageTag: 4029ab0b-c829-4d7c-b359-0762682abcd4
		summarizeBy: none
		sourceColumn: IDCobranza

		annotation SummarizationSetBy = Automatic

	column IDFactura
		isHidden
		dataType: int64
		formatString: 0
		lineageTag: 4982d291-0956-4a68-a67c-a5cc2e111f82
		summarizeBy: none
		sourceColumn: IDFactura

		annotation SummarizationSetBy = Automatic

	column FechaCobro
		dataType: dateTime
		formatString: Short Date
		lineageTag: 3562a63d-1b55-4a54-8129-3dd3ecdb4ced
		summarizeBy: none
		sourceColumn: FechaCobro

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MontoCobrado
		dataType: double
		lineageTag: 9fa11c15-19eb-4f69-baa0-5d596c400a4d
		summarizeBy: sum
		sourceColumn: MontoCobrado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IDCliente
		isHidden
		dataType: int64
		formatString: 0
		lineageTag: b861c964-4872-4e1b-aeed-106fdf8ad51b
		summarizeBy: none
		sourceColumn: IDCliente

		annotation SummarizationSetBy = Automatic

	partition Cobranzas-fe4ca924-e002-427a-8fe7-bfb8c56a73b8 = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Data\AnalisisVentas\Ejer PBI.xlsx"), null, true),
				    Cobranzas_Sheet = Origen{[Item="Cobranzas",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Cobranzas_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"IDCobranza", Int64.Type}, {"IDFactura", Int64.Type}, {"FechaCobro", type date}, {"MontoCobrado", type number}, {"IDCliente", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

